site_name: Andrej-Notes
repo_url: https://github.com/RAravindDS/Andrew-karpathy-MakeMoreSeries
repo_name: RAravindDS/Andrew-karpathy-MakeMoreSeries


theme: 
  name: material 
  logo: assets/andrej.jpg
  favicon: assets/andrej.jpg
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    primary: black

  font:
    text: Roboto

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

nav:
  - Home: 'index.md'
  - 01. Build a Bigram Model: '01-BigramLLM.ipynb'
  - 02. Build MLP: '01-MLP.ipynb'
  - 03. Understand activations and gradients: '1-UnderstandingActivationsGradientMore.ipynb'
  - 04. Understand torch mean: '2-UnderstandingTorchMean.ipynb'
  - 05. Understanding Derivaties: '01-Understanding-Derivaties.ipynb'
  - 06. Neural Net Library: '02-NerualNetLibrary.ipynb'